// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CS_AesKey : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CS_AesKey GetRootAsCS_AesKey(ByteBuffer _bb) { return GetRootAsCS_AesKey(_bb, new CS_AesKey()); }
  public static CS_AesKey GetRootAsCS_AesKey(ByteBuffer _bb, CS_AesKey obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CS_AesKey __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sbyte Iv(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetSbyte(__p.__vector(o) + j * 1) : (sbyte)0; }
  public int IvLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<sbyte> GetIvBytes() { return __p.__vector_as_span<sbyte>(4, 1); }
#else
  public ArraySegment<byte>? GetIvBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public sbyte[] GetIvArray() { return __p.__vector_as_array<sbyte>(4); }
  public sbyte Key(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetSbyte(__p.__vector(o) + j * 1) : (sbyte)0; }
  public int KeyLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<sbyte> GetKeyBytes() { return __p.__vector_as_span<sbyte>(6, 1); }
#else
  public ArraySegment<byte>? GetKeyBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public sbyte[] GetKeyArray() { return __p.__vector_as_array<sbyte>(6); }

  public static Offset<CS_AesKey> CreateCS_AesKey(FlatBufferBuilder builder,
      VectorOffset ivOffset = default(VectorOffset),
      VectorOffset keyOffset = default(VectorOffset)) {
    builder.StartTable(2);
    CS_AesKey.AddKey(builder, keyOffset);
    CS_AesKey.AddIv(builder, ivOffset);
    return CS_AesKey.EndCS_AesKey(builder);
  }

  public static void StartCS_AesKey(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddIv(FlatBufferBuilder builder, VectorOffset ivOffset) { builder.AddOffset(0, ivOffset.Value, 0); }
  public static VectorOffset CreateIvVector(FlatBufferBuilder builder, sbyte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddSbyte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateIvVectorBlock(FlatBufferBuilder builder, sbyte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateIvVectorBlock(FlatBufferBuilder builder, ArraySegment<sbyte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateIvVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<sbyte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartIvVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static void AddKey(FlatBufferBuilder builder, VectorOffset keyOffset) { builder.AddOffset(1, keyOffset.Value, 0); }
  public static VectorOffset CreateKeyVector(FlatBufferBuilder builder, sbyte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddSbyte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateKeyVectorBlock(FlatBufferBuilder builder, sbyte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateKeyVectorBlock(FlatBufferBuilder builder, ArraySegment<sbyte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateKeyVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<sbyte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartKeyVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<CS_AesKey> EndCS_AesKey(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CS_AesKey>(o);
  }
}


static public class CS_AesKeyVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Iv*/, 1 /*sbyte*/, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*Key*/, 1 /*sbyte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
