// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CS_ErrorLog : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CS_ErrorLog GetRootAsCS_ErrorLog(ByteBuffer _bb) { return GetRootAsCS_ErrorLog(_bb, new CS_ErrorLog()); }
  public static CS_ErrorLog GetRootAsCS_ErrorLog(ByteBuffer _bb, CS_ErrorLog obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CS_ErrorLog __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string DeviceInfo { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDeviceInfoBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetDeviceInfoBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetDeviceInfoArray() { return __p.__vector_as_array<byte>(4); }
  public string Message { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMessageBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetMessageBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetMessageArray() { return __p.__vector_as_array<byte>(6); }
  public string StackTrace { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetStackTraceBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetStackTraceBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetStackTraceArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<CS_ErrorLog> CreateCS_ErrorLog(FlatBufferBuilder builder,
      StringOffset device_infoOffset = default(StringOffset),
      StringOffset messageOffset = default(StringOffset),
      StringOffset stack_traceOffset = default(StringOffset)) {
    builder.StartTable(3);
    CS_ErrorLog.AddStackTrace(builder, stack_traceOffset);
    CS_ErrorLog.AddMessage(builder, messageOffset);
    CS_ErrorLog.AddDeviceInfo(builder, device_infoOffset);
    return CS_ErrorLog.EndCS_ErrorLog(builder);
  }

  public static void StartCS_ErrorLog(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddDeviceInfo(FlatBufferBuilder builder, StringOffset deviceInfoOffset) { builder.AddOffset(0, deviceInfoOffset.Value, 0); }
  public static void AddMessage(FlatBufferBuilder builder, StringOffset messageOffset) { builder.AddOffset(1, messageOffset.Value, 0); }
  public static void AddStackTrace(FlatBufferBuilder builder, StringOffset stackTraceOffset) { builder.AddOffset(2, stackTraceOffset.Value, 0); }
  public static Offset<CS_ErrorLog> EndCS_ErrorLog(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CS_ErrorLog>(o);
  }
}


static public class CS_ErrorLogVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*DeviceInfo*/, false)
      && verifier.VerifyString(tablePos, 6 /*Message*/, false)
      && verifier.VerifyString(tablePos, 8 /*StackTrace*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
