// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CW_CS_Pong : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CW_CS_Pong GetRootAsCW_CS_Pong(ByteBuffer _bb) { return GetRootAsCW_CS_Pong(_bb, new CW_CS_Pong()); }
  public static CW_CS_Pong GetRootAsCW_CS_Pong(ByteBuffer _bb, CW_CS_Pong obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CW_CS_Pong __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Timestamp { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<CW_CS_Pong> CreateCW_CS_Pong(FlatBufferBuilder builder,
      long timestamp = 0) {
    builder.StartTable(1);
    CW_CS_Pong.AddTimestamp(builder, timestamp);
    return CW_CS_Pong.EndCW_CS_Pong(builder);
  }

  public static void StartCW_CS_Pong(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddTimestamp(FlatBufferBuilder builder, long timestamp) { builder.AddLong(0, timestamp, 0); }
  public static Offset<CW_CS_Pong> EndCW_CS_Pong(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CW_CS_Pong>(o);
  }
}


static public class CW_CS_PongVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Timestamp*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
