// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

public enum CW_PKT_Type : ushort
{
  CS_AES_KEY = 0,
  SC_RSA_PUB_KEY = 1,
  SC_PING = 2,
  CS_PONG = 3,
  CS_ERROR_LOG = 4,
};

