// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SC_RsaPubKey : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static SC_RsaPubKey GetRootAsSC_RsaPubKey(ByteBuffer _bb) { return GetRootAsSC_RsaPubKey(_bb, new SC_RsaPubKey()); }
  public static SC_RsaPubKey GetRootAsSC_RsaPubKey(ByteBuffer _bb, SC_RsaPubKey obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SC_RsaPubKey __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public sbyte PubKey(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetSbyte(__p.__vector(o) + j * 1) : (sbyte)0; }
  public int PubKeyLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<sbyte> GetPubKeyBytes() { return __p.__vector_as_span<sbyte>(4, 1); }
#else
  public ArraySegment<byte>? GetPubKeyBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public sbyte[] GetPubKeyArray() { return __p.__vector_as_array<sbyte>(4); }

  public static Offset<SC_RsaPubKey> CreateSC_RsaPubKey(FlatBufferBuilder builder,
      VectorOffset pub_keyOffset = default(VectorOffset)) {
    builder.StartTable(1);
    SC_RsaPubKey.AddPubKey(builder, pub_keyOffset);
    return SC_RsaPubKey.EndSC_RsaPubKey(builder);
  }

  public static void StartSC_RsaPubKey(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddPubKey(FlatBufferBuilder builder, VectorOffset pubKeyOffset) { builder.AddOffset(0, pubKeyOffset.Value, 0); }
  public static VectorOffset CreatePubKeyVector(FlatBufferBuilder builder, sbyte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddSbyte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreatePubKeyVectorBlock(FlatBufferBuilder builder, sbyte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePubKeyVectorBlock(FlatBufferBuilder builder, ArraySegment<sbyte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreatePubKeyVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<sbyte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartPubKeyVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<SC_RsaPubKey> EndSC_RsaPubKey(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SC_RsaPubKey>(o);
  }
}


static public class SC_RsaPubKeyVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*PubKey*/, 1 /*sbyte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
